/* Rendering is separate from course-core.js. Charts introduce one data object
   at a time. All values stay in the browser; no analytics or external scripts. */
(()=>{'use strict';
const C=window.Course,$=id=>document.getElementById(id),TAU=C.TAU;
const ink='#183248',muted='#556d80',teal='#087f78',blue='#2b64be',orange='#bc671b',line='#dce5eb';
const val=id=>Number($(id).value),on=id=>$(id).checked;
const f=(x,n=2)=>Math.abs(x)<1e-10?(0).toFixed(n):x.toFixed(n);
const degree=x=>x*180/Math.PI,complex=z=>`${f(z.re,3)} ${z.im<0?'−':'+'} j${f(Math.abs(z.im),3)}`;
let stage=0,active=null,frame=0,printDetails=[];
function inputs(){document.querySelectorAll('input[type=range]').forEach(e=>{let o=$(e.id+'-value');if(!o)return;const digits=e.dataset.digits;const value=digits===undefined?Number(e.value):Number(e.value).toFixed(Number(digits));o.textContent=`${value} ${e.dataset.unit||''}`.trim();});}
function prep(id){const el=$(id);if(!el||!el.getClientRects().length||el.closest('[hidden]'))return null;const w=el.getBoundingClientRect().width,h=Number(el.dataset.h),dpr=Math.min(window.devicePixelRatio||1,2);
 el.width=Math.round(w*dpr);el.height=Math.round(h*dpr);el.style.height=h+'px';const g=el.getContext('2d');g.setTransform(dpr,0,0,dpr,0,0);g.clearRect(0,0,w,h);g.font='14px system-ui, sans-serif';g.textBaseline='middle';g.lineWidth=1.5;return{g,w,h,el};}
function text(g,s,x,y,color=ink,size=14,align='left'){g.fillStyle=color;g.font=`${size}px system-ui, sans-serif`;g.textAlign=align;g.fillText(s,x,y);g.textAlign='left';}
function path(g,pts,color=teal,width=2,dash=[]){g.beginPath();g.strokeStyle=color;g.lineWidth=width;g.setLineDash(dash);let started=false;pts.forEach(([x,y])=>{if(!Number.isFinite(y)){started=false;return;}if(!started){g.moveTo(x,y);started=true;}else g.lineTo(x,y);});g.stroke();g.setLineDash([]);}
function dot(g,x,y,r=4,color=teal){g.beginPath();g.arc(x,y,r,0,TAU);g.fillStyle=color;g.fill();}
function arrow(g,x,y,dx,dy,color=teal,width=2){path(g,[[x,y],[x+dx,y+dy]],color,width);const a=Math.atan2(dy,dx),b=7;path(g,[[x+dx-b*Math.cos(a-.45),y+dy-b*Math.sin(a-.45)],[x+dx,y+dy],[x+dx-b*Math.cos(a+.45),y+dy-b*Math.sin(a+.45)]],color,width);}
function axes(o,{title='',xmin=0,xmax=1,ymin=0,ymax=1,xlabel='',ylabel='',xticks=null,yticks=null}){
 const{g,w,h}=o,L=w<430?48:61,R=19,T=47,B=51,ww=w-L-R,hh=h-T-B,x=v=>L+(v-xmin)/(xmax-xmin)*ww,y=v=>T+(ymax-v)/(ymax-ymin)*hh;
 text(g,title,15,20,ink,w<430?13:14);if(ylabel)text(g,ylabel,L,36,muted,11);
 (yticks||[ymin,(ymin+ymax)/2,ymax]).forEach(v=>{const z=typeof v==='object'?v.v:v,t=typeof v==='object'?v.t:String(Math.round(v*100)/100);path(g,[[L,y(z)],[w-R,y(z)]],line,1);text(g,t,L-8,y(z),muted,11,'right');});
 (xticks||[xmin,(xmin+xmax)/2,xmax]).forEach(v=>{const z=typeof v==='object'?v.v:v,t=typeof v==='object'?v.t:String(Math.round(v*100)/100);path(g,[[x(z),T],[x(z),h-B]],line,.7);text(g,t,x(z),h-B+17,muted,11,'center');});
 text(g,xlabel,L+ww/2,h-13,muted,12,'center');path(g,[[L,T],[L,h-B],[w-R,h-B]],'#9cb1bf',1);return{x,y,L,R,T,B,ww,hh};}
function vectors(id,zs,title,activeIndex=-1,labels=null){const o=prep(id);if(!o)return;const{g,w,h}=o;let cols=Math.min(zs.length,w<430?4:8),rows=Math.ceil(zs.length/cols),cellW=(w-26)/cols,cellH=(h-47)/rows,r=Math.min(24,cellH*.28,cellW*.27);text(g,title,14,20,ink,w<430?12:14);
 zs.forEach((z,i)=>{const x=13+cellW*(i%cols+.5),y=42+cellH*(Math.floor(i/cols)+.4);if(i===activeIndex){g.fillStyle='#fff1ce';g.fillRect(x-cellW*.45,y-cellH*.42,cellW*.9,cellH*.92);}g.beginPath();g.arc(x,y,r,0,TAU);g.strokeStyle='#beced9';g.lineWidth=1;g.stroke();path(g,[[x-r,y],[x+r,y]],line,1);arrow(g,x,y,r*z.re,-r*z.im,i===activeIndex?orange:teal,2);text(g,labels?labels[i]:String(i),x,y+r+13,muted,11,'center');});}
function drawEcho(){let o=prep('echo-c');if(!o)return;const{g,w,h}=o,R=val('echo-r'),t=val('echo-t'),travel=300*t,tau=2*R/300,x0=42,x1=w-38,xx=r=>x0+r/150*(x1-x0),tx=xx(R);text(g,'去程 →     目标反射     ← 回程',15,22,ink,13);path(g,[[x0,85],[tx,85]],blue,2);path(g,[[tx,142],[x0,142]],teal,2);path(g,[[tx,71],[tx,156]],orange,3);text(g,'基站',x0,178,ink,13,'center');text(g,`${R} m`,tx,178,orange,13,'center');text(g,'发射端',x0,57,muted,11,'center');
 let msg;if(travel<R){dot(g,xx(travel),85,7,blue);msg='波包仍在去程';}else if(travel<2*R){dot(g,xx(2*R-travel),142,7,teal);msg='目标已反射，波包正在返回';}else{dot(g,x0,142,8,orange);msg='回波已经到达共址接收机';}
 $('echo-read').textContent=`t = ${f(t,3)} μs：${msg}。目标往返延迟 τ = ${f(tau,3)} μs = ${f(tau*1000,0)} ns；按 cτ/2 换算是 ${R} m。`;
}
function drawIQ(){const ns=val('iq-tau'),tau=ns*1e-9,phi=-TAU*1e6*tau,o=prep('iq-wave');if(o){const a=axes(o,{title:'同一条波：实部的时间平移',xmin:0,xmax:3,ymin:-1.2,ymax:1.2,yticks:[-1,0,1],xlabel:'时间 t / μs',ylabel:'实部（归一化）'}),pts=Array.from({length:241},(_,i)=>i/80);path(o.g,pts.map(t=>[a.x(t),a.y(Math.cos(TAU*t))]),blue,2);path(o.g,pts.map(t=>[a.x(t),a.y(Math.cos(TAU*(t-ns/1000)))]),orange,2,[6,3]);text(o.g,'蓝实线：发射；橙虚线：延迟后',a.L+5,a.T+13,muted,11);}
 const q=prep('iq-phase');if(q){const{g,w,h}=q,x=w/2,y=112,r=62;path(g,[[x-85,y],[x+85,y]],line,1);path(g,[[x,y-85],[x,y+78]],line,1);g.beginPath();g.arc(x,y,r,0,TAU);g.strokeStyle='#c2d2dc';g.stroke();arrow(g,x,y,r,0,blue,2);arrow(g,x,y,r*Math.cos(phi),-r*Math.sin(phi),orange,3);text(g,'H = e^(−j2πfτ)',14,20);text(g,'I',x+91,y,muted,13);text(g,'Q',x,y-91,muted,13);text(g,`角度 ${f(degree(C.wrap(phi)),0)}°`,x,199,orange,13,'center');}
 $('iq-read').textContent=`延迟 ${ns} ns，相位旋转 ${f(degree(phi),0)}°；只显示一圈时为 ${f(degree(C.wrap(phi)),0)}°。I = ${f(Math.cos(phi),3)}，Q = ${f(Math.sin(phi),3)}；幅度 1、功率 1 都未改变。再增加 1000 ns 会得到同一复向量。`;
}
function drawMatch(){const lag=val('match-lag'),s=C.matched($('match-kind').value,on('match-wrong'),on('match-noise')?.45:0,on('match-second'));
 let o=prep('match-wave');if(o){const a=axes(o,{title:'接收序列 y[n]；浅色区域是当前取出的13点',xmin:0,xmax:79,ymin:-2.5,ymax:2.5,xlabel:'快时间采样 n',yticks:[-2,0,2]});o.g.fillStyle='#e0f0eb';o.g.fillRect(a.x(lag),a.T,a.x(lag+12)-a.x(lag),a.hh);path(o.g,s.y.map((v,n)=>[a.x(n),a.y(v)]),blue,1.7);path(o.g,s.template.map((v,n)=>[a.x(lag+n),a.y(v)]),orange,2,[4,3]);}
 o=prep('match-product');if(o){const a=axes(o,{title:'逐项相乘：y[q+n] × 模板[n]',xmin:0,xmax:12,ymin:-2.5,ymax:2.5,yticks:[-2,0,2],xlabel:'模板内部索引 n'});s.template.forEach((v,j)=>{const p=v*s.y[lag+j];path(o.g,[[a.x(j),a.y(0)],[a.x(j),a.y(p)]],p>=0?teal:orange,5);});}
 o=prep('match-score');if(o){const a=axes(o,{title:'每个候选延迟的归一化相关幅度 |z[q]|',xmin:0,xmax:64,ymin:0,ymax:1.5,xlabel:'候选延迟 q / 格',yticks:[0,.5,1,1.5]});path(o.g,s.z.map((v,q)=>[a.x(q),a.y(Math.abs(v))]),teal,2);dot(o.g,a.x(lag),a.y(Math.abs(s.z[lag])),5,orange);}
 $('match-read').textContent=`当前位置 q = ${lag}，13项乘积平均 z[q] = ${f(s.z[lag],3)}，幅度为 ${f(Math.abs(s.z[lag]),3)}。真值 q = 25 的幅度是 ${f(Math.abs(s.z[25]),3)}。${lag===25?'你正在对齐真实回波。':'先预测移到 q=25 后能否全部同号，再按“移到真实延迟”。'}`;
}
function drawDop(){window.Intuition?.drawSlow();}
function drawArray(){const N=val('arr-n'),a=val('arr-a'),s=val('arr-s'),ar=C.array(N,a,s);vectors('arr-phasors',ar.z,'相邻路径差经补偿后，还剩多少相位？',-1,ar.z.map((_,i)=>'ℓ='+i));let o=prep('arr-beam');if(o){const b=axes(o,{title:'给定入射角，扫描不同接收指向',xmin:-80,xmax:80,ymin:0,ymax:1.05,xticks:[-80,-40,0,40,80],yticks:[0,.5,1],xlabel:'候选接收指向 θ₀ / °',ylabel:'归一化功率'});path(o.g,Array.from({length:321},(_,i)=>{let t=-80+i*.5;return[b.x(t),b.y(C.array(N,a,t).gain)];}),teal,2);dot(o.g,b.x(s),b.y(ar.gain),5,orange);}
 $('arr-read').textContent=`真实方向 ${a}°，接收指向 ${s}°，相邻残余相位 ${f(degree(ar.step),1)}°。归一化相干功率 ${f(ar.gain,3)}（${f(10*Math.log10(Math.max(ar.gain,1e-8)),1)} dB）。所有箭头一致时得分为 1；此归一化不展示增加阵元的绝对链路增益。`;
}
function drawSynthesis(){const k=val('synth-k'),p=val('synth-phase')*Math.PI/180,N=64,X=Array.from({length:4},(_,j)=>C.cis(j===k?p:0));let ys=Array.from({length:N},(_,n)=>X.reduce((s,x,j)=>{const z=C.mul(x,C.cis(TAU*j*n/N));return{re:s.re+z.re,im:s.im+z.im};},{re:0,im:0}));let back=C.dft(ys),o=prep('synth-wave');if(o){const a=axes(o,{title:'四个正交分量相加；只显示实部',xmin:0,xmax:1,ymin:-4.3,ymax:4.3,yticks:[-4,0,4],xlabel:'归一化时间 t/Tu'});path(o.g,ys.map((z,n)=>[a.x(n/N),a.y(z.re)]),blue,2);path(o.g,ys.map((_,n)=>[a.x(n/N),a.y(Math.cos(TAU*k*n/N+p))]),orange,2,[5,3]);text(o.g,'蓝：总和；橙：选中分量',a.L+5,a.T+12,muted,11);}
 $('synth-read').textContent=`用对应复正弦对完整复采样做内积，读回第 k=${k} 个系数：${complex(back[k])}，相位 ${f(degree(Math.atan2(back[k].im,back[k].re)),0)}°。其余三根的恢复系数保持约 1+j0；并不是靠在时间上拆开四段来分离。`;
}
const phaseColor=p=>`hsl(${190+(C.wrap(p)+Math.PI)/TAU*360},65%,48%)`;
const powerColor=t=>{t=Math.max(0,Math.min(1,t));return`rgb(${Math.round(239-231*t)},${Math.round(247-120*t)},${Math.round(251-131*t)})`;};
function heat(id,matrix,type,sel=null){const o=prep(id);if(!o)return;const{g,w,h,el}=o,L=w<430?52:65,R=20,T=48,B=84,ww=w-L-R,hh=h-T-B,rows=matrix.length,cols=matrix[0].length;
 const title=type==='phase'?'相位图：颜色是方向，不是能量':type==='time'?'中间结果：距离 × 观察时刻':'最后结果：距离 × 径向速度';text(g,title,13,20,ink,w<430?12:14);
 for(let i=0;i<rows;i++)for(let j=0;j<cols;j++){let z=matrix[i][j];g.fillStyle=type==='phase'?phaseColor(z):powerColor(type==='time'?z:(10*Math.log10(Math.max(z,1e-5))+50)/50);g.fillRect(L+j*ww/cols,T+i*hh/rows,ww/cols+.35,hh/rows+.35);}
 const xt=type==='phase'?[0,4,8,12,15]:[0,4,8,12,15],yt=[0,4,8,12,15];xt.forEach(j=>text(g,type==='phase'?String(j):f(j*9.375,1),L+(j+.5)*ww/cols,T+hh+17,muted,10,'center'));
 yt.forEach(i=>text(g,type==='rd'?f((7-i)*3.75,2):String(i),L-7,T+(i+.5)*hh/rows,muted,10,'right'));
 text(g,type==='phase'?'子载波 k →':'候选距离 R / m →',L+ww/2,h-10,muted,12,'center');text(g,type==='rd'?'v / m/s ↑':'m ↓',L-8,T-16,muted,11,'right');
 for(let px=0;px<ww;px++){g.fillStyle=type==='phase'?phaseColor(-Math.PI+TAU*px/(ww-1)):powerColor(px/ww);g.fillRect(L+px,T+hh+34,1,9);}
 text(g,type==='phase'?'−π / −180°':type==='time'?'0':'−50 dB',L,T+hh+55,muted,10);text(g,type==='phase'?'0°':type==='time'?'线性功率':'功率：深色更强',L+ww/2,T+hh+55,muted,10,'center');text(g,type==='phase'?'+π / +180°':type==='time'?'1':'0 dB',w-R,T+hh+55,muted,10,'right');
 if(sel){g.strokeStyle=orange;g.lineWidth=3;g.strokeRect(L+sel.k*ww/cols+1,T+sel.m*hh/rows+1,ww/cols-2,hh/rows-2);}
 el._grid={L,T,ww,hh,rows,cols};
}
function drawOfdm(){const R=val('o-r'),v=val('o-v'),base=C.ofdm(R,v),s=on('o-remove')?base:C.ofdm(R,v,false),tau=base.tau,df=C.cfg.df,Tr=C.cfg.Tr;
 const x=base.X[0][1],y=base.Y[0][1],h=base.H[0][1];$('o-cell').innerHTML=[['X',x,'发射符号'],['Y',y,'收到的系数'],['H',h,'Y/X 得到的路径响应']].map(([t,z,d])=>`<div><b>${t}</b><span>${complex(z)}</span><small>${d}；相位 ${f(degree(Math.atan2(z.im,z.re)),0)}°</small></div>`).join('');
 vectors('o-cell-c',[x,y,h],'同一格 m=0,k=1：三个复数，三种角色',-1,['X 发射','Y 接收','H 信道']);
 let o=prep('o-row');if(o){const wrapped=on('o-wrapped'),step=-TAU*df*tau,p=Array.from({length:16},(_,k)=>degree(wrapped?C.wrap(step*k):step*k)),min=wrapped?-180:Math.min(-90,...p),max=wrapped?180:0,a=axes(o,{title:wrapped?'同一行的相位（折回显示）':'同一行的相位（展开显示）',xmin:0,xmax:15,ymin:min,ymax:max,xticks:[0,4,8,12,15],xlabel:'子载波编号 k（相邻差 1 MHz）',ylabel:'相位 / °'});path(o.g,p.map((z,k)=>[a.x(k),a.y(z)]),teal,2);p.forEach((z,k)=>dot(o.g,a.x(k),a.y(z),3,teal));}
 $('o-row-read').textContent=`R = ${f(R,3)} m → τ = ${f(tau*1e9,2)} ns。相邻频率的相位差是 −2π×1 MHz×τ = ${f(-360*df*tau,2)}°。从这个步长反推 τ，再用 R=cτ/2；不是把某个颜色直接换算成距离。`;
 let comp=C.compensation(R,val('o-trial'));vectors('o-residual',comp.arrows,'猜一个距离，补偿后再把箭头相加',-1,comp.arrows.map((_,k)=>'k='+k));
 o=prep('o-range');if(o){const a=axes(o,{title:'对所有候选距离重复刚才的匹配',xmin:0,xmax:140,ymin:0,ymax:1.05,yticks:[0,.5,1],xlabel:'候选距离 R̂ / m',ylabel:'归一化相干功率'});path(o.g,Array.from({length:449},(_,i)=>[a.x(i*140/448),a.y(C.compensation(R,i*140/448).p)]),teal,2);for(let r=0;r<16;r++){let t=r*9.375;if(t<=140)dot(o.g,a.x(t),a.y(C.compensation(R,t).p),3,blue);}dot(o.g,a.x(val('o-trial')),a.y(comp.p),5,orange);}
 $('o-trial-read').textContent=`你猜 R̂ = ${f(val('o-trial'),3)} m；归一化向量和为 ${complex(comp.sum)}，功率 |z|² = ${f(comp.p,4)}。曲线为连续候选；蓝点是 IFFT 的规则格子（相邻 9.375 m）。`;
 o=prep('o-column');if(o){const step=TAU*base.fd*Tr,p=Array.from({length:16},(_,m)=>degree(step*m)),lo=Math.min(-45,...p),hi=Math.max(45,...p),a=axes(o,{title:'固定 k=0，重复观察旋转',xmin:0,xmax:15,ymin:lo,ymax:hi,xticks:[0,4,8,12,15],xlabel:'观察编号 m（相邻差 0.5 ms）',ylabel:'展开相位 / °'});path(o.g,p.map((z,m)=>[a.x(m),a.y(z)]),teal,2);p.forEach((z,m)=>dot(o.g,a.x(m),a.y(z),3));}
 $('o-column-read').textContent=`v = ${f(v,2)} m/s → f_D = ${f(base.fd,1)} Hz。每拍相位增加 ${f(360*base.fd*Tr,1)}°。固定 k 时，初始相位只加一个常量，转速才给出多普勒。`;
 let k=val('o-k'),m=val('o-m');heat('o-grid',s.H.map(row=>row.map(z=>Math.atan2(z.im,z.re))),'phase',{k,m});let z=s.H[m][k];$('o-grid-read').textContent=`当前读的是 ${on('o-remove')?'H = Y/X（已去数据）':'Y（未去数据）'}[m=${m},k=${k}]：时刻 ${f(m*.5,1)} ms，频率偏移 ${k} MHz；复数 ${complex(z)}；相位 ${f(degree(Math.atan2(z.im,z.re)),1)}°，功率 ${f(C.power(z),3)}。格子由 m、k 索引，不是目标位置。`;
 heat('o-intermediate',s.A.map(row=>row.map(C.power)),'time');let r=s.best.r,z0=s.A[0][r],z1=s.A[1][r];$('o-inter-read').textContent=`在候选距离 ${f(r*s.dR,3)} m，前两拍复数分别为 ${complex(z0)} 和 ${complex(z1)}。${on('o-remove')?'模平方相近，但方向继续旋转；下一步对复数列做 FFT。':'当前尚未去通信符号，不能把这条结果当成可靠距离估计。'}`;
 heat('o-rd',s.P,'rd',{k:s.best.r,m:7-s.best.d});$('o-rd-read').textContent=`最大匹配响应在 R̂ = ${f(s.best.r*s.dR,3)} m，v̂ = ${f(s.best.d*s.dv,2)} m/s；仿真真值是 ${f(R,3)} m、${f(v,2)} m/s。${on('o-remove')?'橙框只是最大响应标记，尚未经过 CFAR 检验。非整格目标的网格估计会有量化差异。':'警告：通信数据未消除，当前最大峰不可作为正确目标估计。'} 功率按相干匹配参考归一化，色标 −50 至 0 dB。`;
}
const stepNames=['一格','一行','距离匹配','一列','相位矩阵','距离–时间','距离–速度'];
function setStep(n,scroll=false){stage=Math.max(0,Math.min(6,n));document.querySelectorAll('[data-panel]').forEach(p=>p.hidden=Number(p.dataset.panel)!==stage);document.querySelectorAll('[data-step]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.step)===stage)));$('o-v-wrap').hidden=stage<3;$('o-prev').disabled=stage===0;$('o-next').disabled=stage===6;$('o-next').textContent=stage===6?'七步已走完':'下一步：'+stepNames[stage+1];$('o-stage-status').textContent=`第 ${stage+1} / 7 步：${stepNames[stage]}`;drawOfdm();if(scroll)document.querySelector(`[data-panel="${stage}"]`).scrollIntoView({block:'start',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}
function drawCF(){let guard=val('cf-guard'),half=8,cut=val('cf-cut'),p=Number($('cf-p').value),powers=C.cfarData($('cf-scenario').value),threshold=C.ca(powers,half,guard,p),min=half+guard,max=79-half-guard;cut=Math.max(min,Math.min(max,cut));$('cf-cut').min=min;$('cf-cut').max=max;$('cf-cut').value=cut;$('cf-cut-value').textContent=cut+' 格';
 let o=prep('cf-c');if(o){const ymax=Math.max(25,...powers,...threshold.filter(Number.isFinite))*1.12,a=axes(o,{title:'原始功率与局部门限；窗口随 CUT 移动',xmin:0,xmax:79,ymin:0,ymax,xlabel:'检测格编号（此处为一维剖面）',ylabel:'线性功率'});for(let i=cut-guard-half;i<=cut+guard+half;i++){o.g.fillStyle=i===cut?'#ffe6bd':Math.abs(i-cut)<=guard?'#e8e3f4':'#ddede7';o.g.fillRect(a.x(i-.45),a.T,a.ww/80,a.hh);}path(o.g,powers.map((v,i)=>[a.x(i),a.y(v)]),blue,1.5);path(o.g,threshold.map((v,i)=>[a.x(i),a.y(v)]),orange,2,[6,3]);dot(o.g,a.x(cut),a.y(powers[cut]),5,teal);text(o.g,'蓝：功率；橙虚线：门限',a.L+3,a.T+12,muted,11);}
 let alpha=C.caFactor(16,p);$('cf-read').textContent=`浅绿=16个训练格，浅紫=保护格，橙底=CUT。当前 CUT=${cut}，功率=${f(powers[cut],3)}；背景平均=${f(threshold[cut]/alpha,3)}；α=${f(alpha,3)}；门限=${f(threshold[cut],3)}。判决：${powers[cut]>threshold[cut]?'超过门限，报警':'未超过门限，不报警'}。这一次判决不等于检出率或虚警率。`;
}
function drawResolution(){const B=val('res-b')*1e6,dr=C.C/(2*B),pad=on('res-pad')?4:1,o=prep('res-c');if(o){const a=axes(o,{title:'带宽决定包络宽度；栅格密度决定点有多密',xmin:0,xmax:120,ymin:0,ymax:1.05,yticks:[0,.5,1],xlabel:'候选距离 / m',ylabel:'单目标归一化响应'});path(o.g,Array.from({length:361},(_,i)=>{let r=i/3;return[a.x(r),a.y(C.sinc((r-60)/dr)**2)];}),teal,2);for(let r=0;r<=120;r+=dr/pad)dot(o.g,a.x(r),a.y(C.sinc((r-60)/dr)**2),pad===1?4:2.5,orange);}
 $('res-read').textContent=`B=${B/1e6} MHz，中心到第一零点的距离尺度为 c/(2B)=${f(dr,3)} m。当前评估点间距 ${f(dr/pad,3)} m；改变评估密度不改变同一带宽下的 sinc² 包络。目标真值固定 60 m。`;
}
function drawGeometry(){const theta=val('geo-angle')*Math.PI/180,p=C.ellipse(40,theta),g0=C.geometry(p.x,p.y,p.vx,p.vy),o=prep('geo-c');if(o){const a=axes(o,{title:'一条路径长度约束，是椭圆而不是一个位置',xmin:-25,xmax:65,ymin:-8,ymax:43,xticks:[-20,0,20,40,60],yticks:[0,20,40],xlabel:'平面位置 x / m',ylabel:'y / m'}),pts=Array.from({length:181},(_,i)=>{let e=C.ellipse(40,Math.PI*i/180);return[a.x(e.x),a.y(e.y)];});path(o.g,pts,line,2);path(o.g,[[a.x(0),a.y(0)],[a.x(p.x),a.y(p.y)],[a.x(40),a.y(0)]],teal,2);dot(o.g,a.x(0),a.y(0),6,blue);dot(o.g,a.x(40),a.y(0),6,blue);dot(o.g,a.x(p.x),a.y(p.y),6,orange);text(o.g,'Tx',a.x(0),a.y(0)+20,blue,12,'center');text(o.g,'Rx',a.x(40),a.y(0)+20,blue,12,'center');const speed=Math.hypot(p.vx,p.vy);arrow(o.g,a.x(p.x),a.y(p.y),p.vx/speed*29,-p.vy/speed*29,orange,2);}
 $('geo-read').textContent=`当前位置 (${f(p.x,2)}, ${f(p.y,2)}) m。去程 ${f(g0.rt,2)} m + 回程 ${f(g0.rr,2)} m = ${f(g0.L,2)} m；绝对路径延迟 ${f(g0.tau*1e9,2)} ns。沿椭圆切向运动的路径变化率为 0，因此这条链路 f_D≈${f(g0.fd,2)} Hz。单凭它无法恢复全部二维速度。`;
}
const redraws={quad:()=>window.Intuition?.drawIQ(),motion:()=>window.Intuition?.drawMotion(),echo:drawEcho,iq:drawIQ,match:drawMatch,dop:drawDop,arr:drawArray,synth:drawSynthesis,o:drawOfdm,cf:drawCF,res:drawResolution,geo:drawGeometry};
function renderAll(){inputs();Object.values(redraws).forEach(fn=>fn());}
function changed(e){inputs();const key=e.target.id.split('-')[0];if(redraws[key])redraws[key]();if(key==='cf'&&e.target.id!=='cf-cut')$('cf-stats').textContent='参数已更改；请重新运行统计检验。';}
document.querySelectorAll('input,select').forEach(e=>e.addEventListener('input',changed));
document.querySelectorAll('[data-step]').forEach(b=>b.addEventListener('click',()=>setStep(+b.dataset.step,true)));$('o-next').onclick=()=>setStep(stage+1,true);$('o-prev').onclick=()=>setStep(stage-1,true);
$('o-default').onclick=()=>{$('o-r').value=37.5;$('o-v').value=7.5;$('o-remove').checked=true;$('o-wrapped').checked=false;$('o-trial').value=0;$('o-k').value=1;$('o-m').value=0;inputs();drawOfdm();};
$('o-align').onclick=()=>{$('o-trial').value=$('o-r').value;inputs();drawOfdm();};$('match-align').onclick=()=>{$('match-lag').value=25;inputs();drawMatch();};$('arr-align').onclick=()=>{$('arr-s').value=$('arr-a').value;inputs();drawArray();};$('dop-still').onclick=()=>{$('dop-v').value=0;inputs();drawDop();};
$('o-grid').addEventListener('pointerdown',e=>{const el=e.currentTarget,a=el._grid;if(!a)return;const b=el.getBoundingClientRect(),x=e.clientX-b.left,y=e.clientY-b.top,k=Math.floor((x-a.L)/a.ww*a.cols),m=Math.floor((y-a.T)/a.hh*a.rows);if(k>=0&&k<16&&m>=0&&m<16){$('o-k').value=k;$('o-m').value=m;inputs();drawOfdm();}});
$('cf-monte').onclick=()=>{let p=Number($('cf-p').value),html='<div class="table-scroll"><table><thead><tr><th>噪声均值</th><th>虚警 / 试验</th><th>实测比例</th><th>95% 区间</th></tr></thead><tbody>';[.25,1,4].forEach((mu,i)=>{const q=C.trials(16,p,50000,mu,31+i*19);html+=`<tr><td>${mu}</td><td>${q.count} / ${q.n}</td><td>${f(q.rate,5)}</td><td>[${f(q.low,5)}, ${f(q.high,5)}]</td></tr>`;});$('cf-stats').innerHTML=html+`</tbody></table></div><p class="small">设计 P_FA=${p}，N=16。不同噪声均值使用不同固定种子；样本波动正常，区间也有覆盖不确定性。</p>`;};
function stop(){if(active){active.b.textContent=active.b.dataset.original;active.b.setAttribute('aria-pressed','false');}active=null;cancelAnimationFrame(frame);}
function tick(t){if(!active)return;const a=active;let dt=Math.min(.08,(t-a.last)/1000||0);a.last=t;if(document.hidden){stop();return;}const rect=a.el.closest('.chapter').getBoundingClientRect();if(rect.bottom<0||rect.top>window.innerHeight){stop();return;}a.raw+=dt*a.rate;let lo=+a.el.min,hi=+a.el.max,step=+a.el.step||1;if(a.raw>hi)a.raw=lo;let next=Math.max(lo,Math.min(hi,lo+Math.round((a.raw-lo)/step)*step));if(Number(a.el.value)!==next){a.el.value=next;changed({target:a.el});}frame=requestAnimationFrame(tick);}
document.querySelectorAll('[data-play]').forEach(b=>{b.dataset.original=b.textContent;b.setAttribute('aria-pressed','false');b.onclick=()=>{if(active?.b===b){stop();return;}stop();const el=$(b.dataset.play);active={b,el,rate:+b.dataset.rate,raw:+el.value,last:performance.now()};b.textContent='暂停';b.setAttribute('aria-pressed','true');frame=requestAnimationFrame(tick);};});
document.querySelectorAll('[data-reset]').forEach(b=>b.onclick=()=>{stop();let el=$(b.dataset.reset);el.value=el.min;changed({target:el});});
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});
$('print-book').onclick=()=>window.print();window.addEventListener('beforeprint',()=>{stop();printDetails=Array.from(document.querySelectorAll('main details')).map(e=>[e,e.open]);printDetails.forEach(([e])=>e.open=true);document.querySelectorAll('.step-panel').forEach(p=>p.hidden=false);renderAll();});window.addEventListener('afterprint',()=>{printDetails.forEach(([e,open])=>e.open=open);printDetails=[];setStep(stage);});
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(renderAll,160);});
function readingProgress(){const top=window.scrollY,total=document.documentElement.scrollHeight-window.innerHeight;$('progress').style.width=(100*top/Math.max(total,1))+'%';let current='start';document.querySelectorAll('.chapter').forEach(s=>{if(s.getBoundingClientRect().top<window.innerHeight*.28)current=s.id;});document.querySelectorAll('.toc nav a').forEach(a=>{if(a.hash==='#'+current)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});}
window.addEventListener('scroll',readingProgress,{passive:true});document.querySelectorAll('.mobile-toc a').forEach(a=>a.onclick=()=>a.closest('details').open=false);
renderAll();setStep(0);readingProgress();
window.ISACCourseUI={setStep,getStage:()=>stage,renderAll,stop};
})();
