const {test}=require('node:test');const a=require('node:assert/strict');const C=require('../course-core.js');
const near=(x,y,t=1e-9)=>a.ok(Math.abs(x-y)<t,`${x} != ${y}`);
test('constants, delay, Doppler and physical bin conversions',()=>{let s=C.ofdm();near(s.tau,250e-9);near(s.fd,250);near(s.dR,9.375);near(s.dv,3.75);});
test('default target at (37.5m,7.5m/s) is bin (4,2)',()=>{let s=C.ofdm();a.equal(s.best.r,4);a.equal(s.best.d,2);near(s.best.p,1);});
test('range and velocity signs incl negative and stationary',()=>{for(let r of [0,2,7,12])for(let d of [-7,-2,0,3,7]){let s=C.ofdm(r*9.375,d*3.75);a.equal(s.best.r,r);a.equal(s.best.d,d);near(s.best.p,1);}});
test('adjacent frequencies rotate -90 degrees in default case',()=>{let h=C.ofdm().H;let z=C.mul(h[0][1],{re:h[0][0].re,im:-h[0][0].im});near(Math.atan2(z.im,z.re),-Math.PI/2);});
test('adjacent slow-time samples rotate +45 degrees',()=>{let h=C.ofdm().H;let z=C.mul(h[1][0],{re:h[0][0].re,im:-h[0][0].im});near(Math.atan2(z.im,z.re),Math.PI/4);});
test('Y=HX and data removal is actual complex division',()=>{let s=C.ofdm();for(let m=0;m<16;m++)for(let k=0;k<16;k++){let z=C.mul(s.H[m][k],s.X[m][k]);near(z.re,s.Y[m][k].re);near(z.im,s.Y[m][k].im);}});
test('unremoved QPSK destroys the coherent single peak',()=>{let s=C.ofdm(37.5,7.5,false);a.ok(s.best.p<.15);});
test('range IFFT preserves temporal phase at the selected range',()=>{let s=C.ofdm();near(C.power(s.A[0][4]),1);near(C.power(s.A[9][4]),1);near(C.wrap(Math.atan2(s.A[1][4].im,s.A[1][4].re)-Math.atan2(s.A[0][4].im,s.A[0][4].re)),Math.PI/4);});
test('off-grid leakage is computed, not drawn',()=>{let s=C.ofdm(4.4*9.375,2.3*3.75);a.ok(s.best.p<.8);a.ok(s.best.p>.2);a.equal(s.best.r,4);a.equal(s.best.d,2);});
test('delay compensation constructive vs cancellation',()=>{near(C.compensation(37.5,37.5).p,1);near(C.compensation(37.5,46.875).p,0);});
test('CP and low-Doppler assumptions cover UI parameter limits',()=>{a.ok(2*140/3e8<C.cfg.Tcp);a.ok((2*26.25/.06)/C.cfg.df<.001);a.ok(26.25*C.cfg.M*C.cfg.Tr<9.375/10);});
test('matched filter true delay and incorrect template',()=>{let s=C.matched();near(s.z[25],1);a.equal(s.z.indexOf(Math.max(...s.z)),25);a.ok(C.matched('barker',true).z[25]<.5);});
test('CFAR scaling, alpha, validation and guard exclusion',()=>{near(C.caFactor(16,.001),8.63882441695,1e-9);a.throws(()=>C.caFactor(0,.01));let x=Array(80).fill(1);x[40]=20;x[41]=1000;let t=C.ca(x);near(t[40],C.caFactor(16,.01));let u=C.ca(x.map(v=>v*4));near(u[40],4*t[40]);});
test('CA-CFAR empirical Pfa for independent exponential samples',()=>{for(let mu of [.25,1,4]){let z=C.trials(16,.01,100000,mu,31);a.ok(Math.abs(z.rate-.01)<5*Math.sqrt(.01*.99/100000));}});
test('array matched steering and broadside null',()=>{near(C.array(8,25,25).gain,1);near(C.array(2,90,0).gain,0);});
test('bistatic path length and gradient agree with finite differences',()=>{let g=C.geometry(20,30,2,-1),dt=1e-6,h=C.geometry(20+2*dt,30-dt);near((h.L-g.L)/dt,-.06*g.fd,1e-6);});
test('moving along an ellipse yields zero path-rate Doppler',()=>{for(let t of [.2,1,2,4]){let p=C.ellipse(40,t),g=C.geometry(p.x,p.y,p.vx,p.vy);near(g.L,80);near(g.fd,0,1e-10);}});
test('sinc at center and first zeros',()=>{near(C.sinc(0),1);near(C.sinc(1),0);near(C.sinc(-1),0);});
