// Dependency-free structural/DOM tests, not native-browser rendering certification.
const {test}=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),C=require('../estimator-core.js');
const html=fs.readFileSync(require.resolve('../theory.html'),'utf8'),script=fs.readFileSync(require.resolve('../estimator.js'),'utf8');
function setup(width=500,core=C){class E{constructor(){this.children=[];this.attrs={};this.events={};this.clientWidth=width;this.value='';this.textContent='';}setAttribute(k,v){this.attrs[k]=String(v);}append(...v){this.children.push(...v);}replaceChildren(...v){this.children=v;}addEventListener(k,f){this.events[k]=f;}fire(k){this.events[k]({target:this});}}
 const els={};for(const [,id]of html.matchAll(/\bid="([^"]+)"/g))els[id]=new E();for(const [id,v]of Object.entries({mode:'fixed',length:8,count:1000,seed:2026}))els['estimator-'+id].value=String(v);const events={};vm.runInNewContext(script,{window:{Estimator:core,addEventListener:(k,f)=>events[k]=f},document:{getElementById:id=>els[id],createElement:()=>new E(),createElementNS:()=>new E()}});return {e:id=>els['estimator-'+id],els,events};}
test('estimator controls independent, defaults and table endpoint agree with all-trial model',()=>{const {e,els}=setup(),model=C.experiment();a.match(e('result').textContent,/固定发射块.*T=8，B=1000，种子=2026/);a.equal(e('summary').children.length,8);a.equal(e('rows').children.length,32);a.equal(e('checkpoints').children.length,model.gaussian.checkpoints.length+model.bpsk.checkpoints.length);a.equal(e('summary').children[3].children[1].textContent,model.gaussian.summary.mse.toFixed(6));a.equal(els['crb-result'].textContent,'');a.equal(els['rate-result'].textContent,'');const initial=e('result').textContent;e('rerun').fire('click');a.equal(e('result').textContent,initial);e('resample').fire('click');a.match(e('result').textContent,/种子=2027/);a.notEqual(e('result').textContent,initial);for(let i=0;i<2;i++){e('reset').fire('click');a.equal(e('result').textContent,initial);}});
test('warning accurately switches fixed/fresh at T3/4; three curves fresh, two fixed',()=>{const {e}=setup();for(const T of ['3','4']){e('length').value=T;e('length').fire('change');a.match(e('warning').textContent,/条件方差.*有限/);a.equal(e('gaussian').children.filter(n=>n.attrs.points).length,2);e('mode').value='fresh';e('mode').fire('change');a.match(e('warning').textContent,/单次平方误差的方差无穷大/);a.equal(e('gaussian').children.filter(n=>n.attrs.points).length,3);e('mode').value='fixed';e('mode').fire('change');}e('mode').value='fresh';e('length').value='8';e('length').fire('change');a.match(e('warning').textContent,/方差有限/);e('count').value='10000';e('count').fire('change');a.match(e('result').textContent,/B=10000/);});
test('invalid/empty/overflow seeds fail visibly, clear stale results and reset recovers',()=>{const {e}=setup();for(const seed of ['', '-1','1.2','4294967296','NaN','Infinity','1e3']){e('seed').value=seed;e('seed').fire('change');a.match(e('result').textContent,/运行失败/);a.equal(e('summary').children.length,0);a.equal(e('gaussian').children.length,0);}e('reset').fire('click');a.equal(e('summary').children.length,8);e('seed').value='4294967295';e('seed').fire('change');a.match(e('result').textContent,/种子=4294967295/);e('resample').fire('click');a.match(e('result').textContent,/种子=0/);});
test('numerical defects are shown rather than silently dropping trials',()=>{const {e}=setup(323,{...C,experiment(){throw new RangeError('zero energy');}});a.match(e('result').textContent,/运行失败.*zero energy/);a.equal(e('rows').children.length,0);a.match(e('warning').textContent,/失败状态/);});
test('responsive viewBox and all plotted values fit axes at narrow widths; resize consumes no random draws',()=>{for(const width of [200,240,270,293,323,388,500,900]){let calls=0;const {e,events}=setup(width,{...C,experiment(v){calls++;return C.experiment(v);}});events.resize();a.equal(calls,1);for(const family of ['gaussian','bpsk']){const svg=e(family);a.equal(svg.attrs.viewBox,`0 0 ${width} 270`);for(const n of svg.children){a.ok(!/NaN|Infinity/.test(JSON.stringify(n.attrs)));if(n.attrs.points)for(const pair of n.attrs.points.split(' ')){const [x,y]=pair.split(',').map(Number);a.ok(x>=0&&x<=width&&y>=0&&y<=270);}}}}});
test('bounded section ordering, accessible controls and no simulation claims in static fallback',()=>{const s=html.slice(html.indexOf('id="estimator-crb"'),html.indexOf('id="rate-crb-bridge"'));a.ok(html.indexOf('id="crb-mechanism"')<html.indexOf('id="estimator-crb"'));a.equal((s.match(/<svg /g)||[]).length,2);for(const id of ['mode','length','count','seed'])a.match(s,new RegExp(`for="estimator-${id}"`));a.match(s,/role="status"/);a.match(s,/本实验参数（独立于/);a.match(s,/增加 B 不增加单次估计的资源/);a.match(s,/7.210331434/);a.match(s,/不是新 2026 结果/);a.match(s,/且与 x 独立/);a.ok(!/setInterval|requestAnimationFrame|Math.random|localStorage|fetch\(/.test(script));const css=fs.readFileSync(require.resolve('../estimator.css'),'utf8');a.match(css,/font:14px/);a.match(css,/@media\(max-width:480px\)/);a.match(css,/focus-visible/);});
