const {test}=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..');
function resolution(){const els={};for(const id of ['bw','tm','bwval','tmval','dr','dv','ratio','lineA','lineB','labnote'])els[id]={value:id==='bw'?100:20,textContent:'',attrs:{},events:{},setAttribute(k,v){this.attrs[k]=v;},addEventListener(k,v){this.events[k]=v;}};vm.runInNewContext(fs.readFileSync(path.join(root,'resolution.js'),'utf8'),{document:{getElementById:id=>els[id]}});return els;}
test('migrated B/T supplement retains default dimensions and separate analytical responses',()=>{const e=resolution();a.equal(e.dr.textContent,'1.50 m');a.equal(e.dv.textContent,'0.268 m/s');a.equal(e.ratio.textContent,'1.33');for(const id of ['lineA','lineB']){a.equal((e[id].attrs.d.match(/L/g)||[]).length,600);a.ok(!/NaN|Infinity/.test(e[id].attrs.d));}a.notEqual(e.lineA.attrs.d,e.lineB.attrs.d);});
test('bandwidth only changes range scale; coherent duration only changes velocity scale',()=>{const e=resolution(),initial=e.lineA.attrs.d;e.bw.value=200;e.bw.events.input();a.equal(e.dr.textContent,'0.75 m');a.equal(e.dv.textContent,'0.268 m/s');a.notEqual(e.lineA.attrs.d,initial);const range=e.lineA.attrs.d;e.tm.value=40;e.tm.events.input();a.equal(e.dr.textContent,'0.75 m');a.equal(e.dv.textContent,'0.134 m/s');a.equal(e.lineA.attrs.d,range);});
test('supplement prose does not claim the independent curves are a two-target detection result',()=>{const h=fs.readFileSync(path.join(root,'resolution.html'),'utf8');for(const s of ['各目标单独响应','相位相关的交叉项','本页不模拟该合成、检测器或双目标分辨概率'])a.ok(h.includes(s));});
function catalog(){const input={value:'',events:{},addEventListener(k,v){this.events[k]=v;},focus(){this.focused=true;}},form={hidden:true,events:{},addEventListener(k,v){this.events[k]=v;}},count={},empty={},cards=['相位 I/Q','时钟与定位','导频与距离'].map(s=>({hidden:false,dataset:{search:s}})),groups=[{querySelectorAll:()=>cards.slice(0,1)},{querySelectorAll:()=>cards.slice(1)}];const document={querySelector:()=>form,querySelectorAll:selector=>selector==='[data-search]'?cards:groups,getElementById:id=>({'experiment-query':input,'experiment-count':count,'experiment-empty':empty})[id]};vm.runInNewContext(fs.readFileSync(path.join(root,'catalog.js'),'utf8'),{document});return{input,form,count,empty,cards,groups};}
test('catalog enhancement filters existing native cards and announces result count',()=>{const e=catalog();a.equal(e.form.hidden,false);a.equal(e.count.textContent,'显示 3 / 3 个机制实验');e.input.value=' 时钟 ';e.input.events.input();a.deepEqual(e.cards.map(c=>c.hidden),[true,false,true]);a.equal(e.count.textContent,'显示 1 / 3 个机制实验');a.equal(e.empty.hidden,true);a.equal(e.groups[0].hidden,true);});
test('catalog empty state and reset restore all content without navigation',()=>{const e=catalog();e.input.value='不存在';e.input.events.input();a.equal(e.empty.hidden,false);a.equal(e.count.textContent,'显示 0 / 3 个机制实验');e.form.events.reset();a.equal(e.input.value,'');a.equal(e.input.focused,true);a.ok(e.cards.every(c=>!c.hidden));a.ok(e.groups.every(g=>!g.hidden));a.equal(e.empty.hidden,true);let prevented=false;e.form.events.submit({preventDefault(){prevented=true;}});a.equal(prevented,true);});
