const {test}=require('node:test');
const assert=require('node:assert/strict');
const B=require('../intuition-core.js'),C=require('../course-core.js');
const near=(a,b,t=1e-10)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`);
test('z=j produces a real negative sine, not a zero RF signal',()=>{near(B.rf(0,1,0),0);near(B.rf(0,1,Math.PI/2),-1);near(B.rf(0,1,3*Math.PI/2),1);});
test('two coefficients are available at different quarter-cycle instants',()=>{for(const [i,q] of [[.2,.9],[-.8,.1],[1,-1]]){near(B.rf(i,q,0),i);near(B.rf(i,q,Math.PI/2),-q);}});
test('Cartesian synthesis equals amplitude/phase real projection',()=>{for(const i of [-1,-.2,.4,1])for(const q of [-1,.3,1])for(const theta of [0,.5,1,4]){const p=B.polar(i,q);near(B.rf(i,q,theta),p.amplitude*Math.cos(theta+p.phase));}});
test('zero amplitude has no defined phase',()=>{assert.equal(B.polar(0,0).phase,null);near(B.quadrature(0,0).meanRFPower,0);});
test('numerical projection recovers both signed coefficients',()=>{for(const i of [-1,0,.45,1])for(const q of [-1,0,.7,1]){const s=B.quadrature(i,q);near(s.recoveredI,i);near(s.recoveredQ,q);}});
test('positive LO phase rotates recovered coordinates negatively',()=>{const i=.6,q=.8,d=Math.PI/4,s=B.quadrature(i,q,d);near(s.recoveredI,i*Math.cos(d)+q*Math.sin(d));near(s.recoveredQ,q*Math.cos(d)-i*Math.sin(d));});
test('LO reference does not change the transmitted real samples',()=>{const a=B.quadrature(.6,.8),b=B.quadrature(.6,.8,Math.PI/3);a.samples.forEach((s,n)=>near(s.s,b.samples[n].s));});
test('passband average squared voltage is half envelope squared magnitude',()=>{for(const [i,q] of [[0,1],[1,1],[.6,.8],[-1,.2]])near(B.quadrature(i,q).meanRFPower,(i*i+q*q)/2);});
test('quadrature basis cross projection is zero with unit self gain',()=>{const a=B.quadrature(1,0),b=B.quadrature(0,1);near(a.recoveredI,1);near(a.recoveredQ,0);near(b.recoveredI,0);near(b.recoveredQ,1);});
test('four QPSK pairs are distinct, normalized and recoverable',()=>{assert.equal(new Set(Object.values(B.symbols).map(z=>`${z.i},${z.q}`)).size,4);for(const s of Object.values(B.symbols)){near(B.polar(s.i,s.q).envelopePower,1);near(B.quadrature(s.i,s.q).recoveredQ,s.q);}});
test('default 0.5 ms motion is 3.75 mm, 7.50 mm path, 45 degrees',()=>{const s=B.pathState(7.5,.0005);near(s.lambda,.06);near(s.deltaR,-.00375);near(s.deltaL,-.0075);near(s.phaseChange,Math.PI/4);near(s.fd,250);});
test('half wavelength radial motion returns to identical IQ direction',()=>{const s=B.pathState(7.5,.004);near(s.deltaR,-.03);near(s.turns,1);near(s.z.re,1);near(s.z.im,0);});
test('approaching and receding reverse Q while preserving I at equal times',()=>{const a=B.pathState(7.5,.0013),b=B.pathState(-7.5,.0013);near(a.z.re,b.z.re);near(a.z.im,-b.z.im);near(a.fd,-b.fd);});
test('stationary target does not rotate relative to arbitrary initial phase',()=>{const s=B.pathState(0,.008,5e9,37.5,.3);near(s.phaseChange,0);near(s.z.re,Math.cos(.3));near(s.fd,0);});
test('path derivative gives same Doppler as phase derivative',()=>{const dt=1e-7,a=B.pathState(3.75,.001),b=B.pathState(3.75,.001+dt);near((b.phaseChange-a.phaseChange)/(B.TAU*dt),a.fd,1e-7);near(-(b.L-a.L)/(.06*dt),a.fd,1e-5);});
test('slow-time bridge agrees with original OFDM temporal phase axis',()=>{const a=B.slowTime(7.5),b=C.ofdm();a.samples.forEach((s,m)=>{near(s.z.re,b.H[m][0].re);near(s.z.im,b.H[m][0].im);});});
test('initial reflection phase cancels in the adjacent-sample product',()=>{const s=B.slowTime(7.5,.0005,16,.83).samples;for(let m=0;m<15;m++){const re=s[m+1].z.re*s[m].z.re+s[m+1].z.im*s[m].z.im,im=s[m+1].z.im*s[m].z.re-s[m+1].z.re*s[m].z.im;near(Math.atan2(im,re),Math.PI/4);}});
test('4 ms sampling aliases a 250 Hz rotation to a constant sequence',()=>{const s=B.slowTime(7.5,.004);assert.equal(s.ambiguous,true);near(s.apparentFd,0);near(s.apparentV,0);s.samples.forEach(z=>{near(z.z.re,1);near(z.z.im,0);});});
test('Nyquist half-turn boundary is explicitly ambiguous',()=>{const s=B.slowTime(15,.001);assert.equal(s.ambiguous,true);near(Math.abs(s.shortStep),Math.PI);});
test('fast-time toy correlation really computes the displayed complex sample',()=>{for(const v of [-15,0,7.5,26.25])for(const m of [0,1,7,15]){const p=B.probeSnapshot(v,.0005,m);near(p.z.re,p.state.z.re);near(p.z.im,p.state.z.im);near(p.z.re*p.z.re+p.z.im*p.z.im,1);}});
test('time and carrier parameters are validated',()=>{assert.throws(()=>B.rf(NaN,1,0));assert.throws(()=>B.pathState(1,-1));assert.throws(()=>B.pathState(1,1,0));assert.throws(()=>B.slowTime(1,0));assert.throws(()=>B.quadrature(1,0,0,4));});
