// Dependency-free DOM execution; not a real browser, rendering or keyboard certification.
const {test}=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),C=require('../near-field-core.js');
const html=fs.readFileSync(require.resolve('../near-field.html'),'utf8'),script=fs.readFileSync(require.resolve('../near-field.js'),'utf8');
function setup(width=720){class E{constructor(){this.children=[];this.attrs={};this.events={};this.clientWidth=width;this.value='';this.textContent='';}setAttribute(k,v){this.attrs[k]=String(v);}append(...n){this.children.push(...n);}replaceChildren(...n){this.children=n;}addEventListener(t,f){this.events[t]=f;}fire(t){a.ok(this.events[t]);this.events[t]({target:this});}}
const els={},events={};for(const [,id]of html.matchAll(/\bid="([^"]+)"/g))els[id]=new E();els['nf-n'].value='129';els['nf-range'].value='4';vm.runInNewContext(script,{window:{NearField:C,addEventListener:(type,f)=>events[type]=f},document:{getElementById:id=>{a.ok(els[id],id);return els[id];},createElement:()=>new E(),createElementNS:()=>new E()}});return {els,events};}
function rows(e,id){return e[id].children.map(n=>n.children.map(n=>n.textContent));}
test('defaults, repeated controls/reset and resizing keep numerical DOM synchronized',()=>{const {els:e,events}=setup(),initial=e['nf-result'].textContent;a.match(initial,/81.92 m/);a.match(initial,/0.13230073/);a.match(initial,/3.675161e-1/);a.equal(rows(e,'nf-metrics').length,5);a.equal(rows(e,'nf-phases').length,5);a.equal(rows(e,'nf-samples').find(r=>r[0]==='8')[1],'0.2027350052');
for(const N of [33,65,129]){e['nf-n'].value=String(N);e['nf-n'].fire('change');for(const r of [4,4.5,8,20,40]){e['nf-range'].value=String(r);e['nf-range'].fire('input');a.equal(e['nf-range-out'].textContent,`${r} m`);const m=C.metrics(N,r);a.match(e['nf-result'].textContent,new RegExp(m.planeMatch.toFixed(8).replace('.','\\.')));const samples=rows(e,'nf-samples');a.equal(samples.find(row=>row[0]===String(r))[1],'1.0000000000');for(const row of samples){a.equal(row[2],m.planeMatch.toFixed(10));a.equal(row[3],'1.0000000000');}a.equal(rows(e,'nf-phases')[2][2],'0.000000000');}}
for(let i=0;i<3;i++){e['nf-reset'].fire('click');a.equal(e['nf-result'].textContent,initial);a.equal(e['nf-n'].value,'129');a.equal(e['nf-range'].value,'4');events.resize();a.equal(e['nf-result'].textContent,initial);}});
test('responsive SVG geometry is finite and bounded; references are computed constants',()=>{for(const width of [240,270,293,323,358,388,720,950]){const {els:e}=setup(width);for(const N of [33,129])for(const r of [4,40]){e['nf-n'].value=String(N);e['nf-range'].value=String(r);e['nf-range'].fire('input');for(const [id,H]of [['nf-response',310],['nf-phase',280]]){const svg=e[id];a.equal(svg.attrs.viewBox,`0 0 ${width} ${H}`);a.equal(svg.children.filter(n=>n.attrs.id===`${id}-title`).length,1);for(const n of svg.children){a.ok(!/NaN|Infinity/.test(JSON.stringify(n.attrs)));if(n.attrs.points)for(const pair of n.attrs.points.split(' ')){const [x,y]=pair.split(',').map(Number);a.ok(x>=0&&x<=width&&y>=0&&y<=H,`${id} ${pair}`);}}}const curves=e['nf-response'].children.filter(n=>n.attrs.points);a.equal(curves.length,3);for(const curve of curves.slice(0,2))a.equal(new Set(curve.attrs.points.split(' ').map(v=>v.split(',')[1])).size,1);a.ok(curves[0].attrs['stroke-dasharray']);a.ok(curves[1].attrs['stroke-dasharray']);const ticks=e['nf-response'].children.filter(n=>n.attrs.y==='275');a.equal(ticks.length,width<500?3:5);}}a.match(fs.readFileSync(require.resolve('../near-field.css'),'utf8'),/font-size:14px/);});
test('native labeled controls, static fallback, accessible charts/tables and no autoplay',()=>{for(const id of ['nf-n','nf-range'])a.match(html,new RegExp(`for="${id}"`));a.match(html,/<select id="nf-n">/);a.match(html,/id="nf-range" min="4" max="40" step="0.5" value="4"/);a.match(html,/type="button" id="nf-reset"/);a.match(html,/role="status" aria-live="polite"/);a.match(html,/<noscript>/);for(const id of ['nf-response','nf-phase'])a.match(html,new RegExp(`aria-labelledby="${id}-title ${id}-desc"`));a.equal((html.match(/role="region"/g)||[]).length,3);a.equal((html.match(/tabindex="0"/g)||[]).length,3);a.ok(!/setInterval|requestAnimationFrame|Math.random|fetch\(/.test(script));a.match(html,/不是 CRB/);a.match(html,/2025-09-23/);a.match(html,/不是 2026 年新论文/);a.match(html,/G=βaaᵀ，而不是 βaaᴴ/);});
