// Dependency-free DOM harness, not a browser, layout engine or accessibility audit.
const {test}=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),C=require('../network-core.js');
const defaults={x:20,y:35,layout:'spread',count:3,mode:'reciprocal',step:1,sigma:0,extra:0,b1:10,b2:-15,b3:20};
function setup(width=720){class E{constructor(){this.children=[];this.attrs={};this.events={};this.clientWidth=width;this.value='';this.textContent='';}setAttribute(k,v){this.attrs[k]=String(v);}append(...n){this.children.push(...n);}replaceChildren(...n){this.children=n;}addEventListener(t,f){this.events[t]=f;}fire(t){this.events[t]({target:this});}}
const html=fs.readFileSync(require.resolve('../network-clock.html'),'utf8'),els={};for(const [,id]of html.matchAll(/\bid="([^"]+)"/g))els[id]=new E();for(const [id,v]of Object.entries(defaults))els['net-'+id].value=String(v);let computations=0;vm.runInNewContext(fs.readFileSync(require.resolve('../network.js'),'utf8'),{window:{NetworkISAC:{...C,experiment:o=>{computations++;return C.experiment(o);}},addEventListener(){}},document:{getElementById:id=>{a.ok(els[id],id);return els[id];},createElement:()=>new E(),createElementNS:()=>new E()},setTimeout,clearTimeout});return {e:els,computations:()=>computations};}
const rows=e=>e.children.map(r=>r.children.map(c=>c.textContent));
test('DOM defaults show exact correction, all three comparisons and scalar tables',()=>{const {e}=setup();a.match(e['net-result'].textContent,/\(20, 35\).*RMS 0.000 m/);a.equal(e['net-comparison'].children.length,3);a.equal(e['net-links'].children.length,3);a.equal(e['net-undetermined'].children.length,2);a.equal(e['net-probes'].children.length,9);a.equal(rows(e['net-links'])[0][4],'2.99792458');a.match(e['net-warning'].textContent,/不是检测\/定位成功/);});
test('DOM mode changes use same observations and cached numerical grid; collinear mirrors displayed',()=>{const h=setup(),e=h.e,initial=rows(e['net-links']);e['net-mode'].value='ignore';e['net-mode'].fire('change');a.equal(h.computations(),1);a.match(e['net-result'].textContent,/位置误差 4.123/);e['net-mode'].value='oracle';e['net-mode'].fire('change');a.equal(h.computations(),1);a.deepEqual(rows(e['net-links']),initial);e['net-layout'].value='line';e['net-layout'].fire('change');a.match(e['net-warning'].textContent,/镜像/);const rr=rows(e['net-minima']);a.ok(rr.some(r=>r[1]==='20'&&r[2]==='-35'));a.ok(rr.some(r=>r[1]==='20'&&r[2]==='35'));});
test('DOM every numeric control, noisy resample and repeated reset are deterministic',()=>{const {e}=setup(),initial=e['net-result'].textContent;for(const [id,v]of Object.entries({x:30.5,y:-12.5,sigma:2,extra:6,b1:-5,b2:3,b3:-20})){e['net-'+id].value=String(v);e['net-'+id].fire('input');a.equal(e['net-'+id+'-out'].textContent,String(v));}a.match(e['net-warning'].textContent,/破坏/);const before=rows(e['net-links']);e['net-resample'].fire('click');a.notDeepEqual(rows(e['net-links']),before);a.match(e['net-seed'].textContent,/种子 2/);for(let i=0;i<2;i++){e['net-reset'].fire('click');a.equal(e['net-result'].textContent,initial);a.match(e['net-seed'].textContent,/种子 1/);for(const [id,v]of Object.entries(defaults))a.equal(e['net-'+id].value,String(v));}});
test('DOM receiver count warns about continuum and two-path ambiguity; half-metre grid runs',()=>{const {e}=setup();e['net-count'].value='1';e['net-count'].fire('change');a.equal(e['net-links'].children.length,1);a.match(e['net-warning'].textContent,/一条椭圆/);e['net-count'].value='2';e['net-count'].fire('change');a.match(e['net-warning'].textContent,/多交点/);e['net-step'].value='.5';e['net-step'].fire('change');a.match(e['net-seed'].textContent,/401×401.*0.5 m/);});
test('DOM nonreciprocity exposes clock contamination; impossible ellipse and singular point warnings',()=>{const {e}=setup();e['net-extra'].value='6';e['net-extra'].fire('input');a.equal(rows(e['net-links'])[0][5],'-0.007');e['net-reset'].fire('click');e['net-layout'].value='line';e['net-x'].value='-20';e['net-y'].value='0';e['net-mode'].value='ignore';for(const id of ['b1','b2','b3'])e['net-'+id].value='-30';e['net-mode'].fire('change');a.match(e['net-warning'].textContent,/小于两站直线距离/);e['net-x'].value='-70';e['net-x'].fire('input');a.match(e['net-diagnostic'].textContent,/未定义/);});
test('DOM actual-width SVG and nested finite paths; dense grid display remains bounded',()=>{function walk(e){return [e,...e.children.flatMap(walk)];}for(const width of [240,270,323,388,720,950]){const {e}=setup(width);for(const id of ['net-geometry','net-heatmap']){a.equal(e[id].attrs.viewBox,`0 0 ${width} ${width+8}`);const nodes=walk(e[id]);a.ok(nodes.every(n=>!(/NaN|Infinity|undefined/.test(JSON.stringify(n.attrs)))));a.ok(nodes.some(n=>n.attrs['clip-path']));}a.ok(walk(e['net-heatmap']).filter(n=>n.attrs.d).length<=16);}});
test('static semantic controls, axes and source caveats survive without JS; scripts have no network or autoplay',()=>{const html=fs.readFileSync(require.resolve('../network-clock.html'),'utf8'),js=fs.readFileSync(require.resolve('../network.js'),'utf8');for(const id of Object.keys(defaults))a.match(html,new RegExp(`for="net-${id}"`));a.match(html,/<noscript>/);a.match(html,/role="status"/);a.match(html,/图2–6.*排除了失败试验/);a.match(html,/不是 SCPD 复现/);a.match(html,/局部 Jacobian 满秩不保证全局唯一/);a.ok(!/setInterval|requestAnimationFrame|fetch\(|XMLHttpRequest/.test(js));});
test('all local HTML links and fragment targets resolve, including existing-page entry links',()=>{for(const file of ['network-clock.html','foundations.html','theory.html']){const h=fs.readFileSync(require.resolve('../'+file),'utf8');for(const [,href]of h.matchAll(/href="([^"]+)"/g)){if(/^(https?:|mailto:)/.test(href))continue;const [target,hash]=href.split('#'),name=target||file;if(!/\.html$/.test(name))continue;const text=fs.readFileSync(require.resolve('../'+name),'utf8');if(hash)a.ok(text.includes(`id="${hash}"`),`${file}: ${href}`);}}});

test('DOM heatmap legend has opaque backing and candidate labels retain contrasting halos at narrow widths',()=>{function walk(e){return [e,...e.children.flatMap(walk)];}for(const width of [240,323,388,720]){const {e}=setup(width),nodes=walk(e['net-heatmap']),back=nodes.find(n=>n.attrs['data-heatmap-legend-backing']),legend=nodes.find(n=>n.attrs['data-heatmap-legend']);a.ok(back&&legend);a.equal(back.attrs.fill,'#ffffff');a.ok(!('opacity' in back.attrs));a.equal(+back.attrs.height,22);a.ok(+back.attrs.y + +back.attrs.height<=24,'legend stays above plot and cannot hide plotted candidates');a.ok(+back.attrs.x+ +back.attrs.width<=width);a.ok(+legend.attrs.x>+back.attrs.x);a.ok(+legend.attrs.y>+back.attrs.y&&+legend.attrs.y<+back.attrs.y+ +back.attrs.height);a.ok(e['net-heatmap'].children.indexOf(back)<e['net-heatmap'].children.indexOf(legend));for(const id of ['net-geometry','net-heatmap']){const labels=walk(e[id]).filter(n=>n.attrs['data-candidate-label']);a.ok(labels.length>0);for(const label of labels){a.equal(label.attrs.stroke,'#ffffff');a.equal(label.attrs['stroke-width'],'4');a.equal(label.attrs['paint-order'],'stroke fill');a.equal(label.attrs.style,'font-weight:700');}}}});
