// Dependency-free DOM smoke tests; no claim of actual browser rendering or keyboard QA.
const {test}=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),C=require('../pilot-core.js');
function setup(width=720){class E{constructor(){this.children=[];this.attrs={};this.events={};this.clientWidth=width;this.value='';this.checked=false;this.textContent='';}setAttribute(k,v){this.attrs[k]=String(v);}append(...n){this.children.push(...n);}replaceChildren(...n){this.children=n;}addEventListener(t,f){this.events[t]=f;}fire(t){this.events[t]({target:this});}}
 const html=fs.readFileSync(require.resolve('../pilot-design.html'),'utf8'),els={};for(const [,id]of html.matchAll(/\bid="([^"]+)"/g))els[id]=new E();for(const [id,v]of [['q',4],['offset',0],['phase',0],['range',40],['step',.25],['candidate',2.5]])els['pilot-'+id].value=String(v);els['pilot-show-full'].checked=els['pilot-show-block'].checked=true;
 vm.runInNewContext(fs.readFileSync(require.resolve('../pilot.js'),'utf8'),{window:{Pilot:C,addEventListener(){}},document:{getElementById:id=>{a.ok(els[id],id);return els[id];},createElement:()=>new E(),createElementNS:()=>new E()},setTimeout,clearTimeout});return els;}
test('DOM smoke: defaults, all controls, checkboxes, offset clamping and repeated reset',()=>{const e=setup(),initial=e['pilot-result'].textContent;a.match(initial,/2.5、40、77.5、115/);a.equal(e['pilot-data'].children.length,16);a.equal(e['pilot-scores'].children.length,601);
 e['pilot-q'].value='8';e['pilot-q'].fire('change');a.equal(e['pilot-offset'].children.length,8);a.equal(e['pilot-data'].children.length,8);a.match(e['pilot-result'].textContent,/18.75 m/);
 e['pilot-offset'].value='7';e['pilot-offset'].fire('change');e['pilot-q'].value='2';e['pilot-q'].fire('change');a.equal(e['pilot-offset'].value,'1');e['pilot-phase'].value=String(Math.PI/2);e['pilot-phase'].fire('change');
 e['pilot-range'].value='90';e['pilot-range'].fire('input');a.match(e['pilot-result'].textContent,/真值 90 m/);e['pilot-candidate'].value='75';e['pilot-candidate'].fire('input');a.match(e['pilot-selected'].textContent,/手选 75 m/);e['pilot-step'].value='0.1';e['pilot-step'].fire('change');a.equal(e['pilot-scores'].children.length,1501);
 for(const id of ['pilot-show-full','pilot-show-block']){e[id].checked=false;e[id].fire('change');}a.equal(e['pilot-response'].children.filter(n=>n.attrs.points).length,1);a.equal(e['pilot-summary'].children.length,3);
 for(let i=0;i<2;i++){e['pilot-reset'].fire('click');a.equal(e['pilot-result'].textContent,initial);a.equal(e['pilot-offset'].value,'0');a.equal(e['pilot-phase'].value,'0');a.equal(e['pilot-scores'].children.length,601);a.equal(e['pilot-show-full'].checked,true);}});
test('DOM smoke: actual-width viewBoxes, finite bounded points, reduced ticks and 14px CSS labels',()=>{for(const width of [240,270,293,323,358,388,720,950]){const e=setup(width);for(const [id,H]of [['pilot-mask',240],['pilot-response',290]]){const svg=e[id];a.equal(svg.attrs.viewBox,`0 0 ${width} ${H}`);for(const n of svg.children){a.ok(!/NaN|Infinity/.test(JSON.stringify(n.attrs)));if(n.attrs.points)for(const pair of n.attrs.points.split(' ')){const [x,y]=pair.split(',').map(Number);a.ok(x>=0&&x<=width&&y>=0&&y<=H);}}}const ticks=e['pilot-response'].children.filter(n=>n.attrs.y==='261');a.equal(ticks.length,width<500?3:6);}a.match(fs.readFileSync(require.resolve('../pilot.css'),'utf8'),/font-size:14px/);});
test('static accessibility and navigation hooks use native controls, labels and no autoplay',()=>{const h=fs.readFileSync(require.resolve('../pilot-design.html'),'utf8');for(const id of ['q','offset','phase','range','step','candidate'])a.match(h,new RegExp(`for="pilot-${id}"`));a.match(h,/id="pilot-candidate"[^>]*step="0.25"/);a.match(h,/type="button"/);a.match(h,/role="status"/);a.match(h,/aria-label="案例目录"/);a.match(h,/href="theory.html#research-method"/);a.ok(!/setInterval|requestAnimationFrame/.test(fs.readFileSync(require.resolve('../pilot.js'),'utf8')));});
