// Dependency-free DOM checks. Not browser, layout or screen-reader certification.
const {test}=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),C=require('../sbfd-core.js');
const html=fs.readFileSync(require.resolve('../sbfd-resource.html'),'utf8'),js=fs.readFileSync(require.resolve('../sbfd.js'),'utf8');
function setup(width=720){class E{constructor(){this.children=[];this.attrs={};this.events={};this.clientWidth=width;this.value='';this.textContent='';}setAttribute(k,v){this.attrs[k]=String(v);}append(...n){this.children.push(...n);}replaceChildren(...n){this.children=n;}addEventListener(t,f){this.events[t]=f;}fire(t){this.events[t]({target:this});}}
const e={},events={};for(const [,id]of html.matchAll(/\bid="([^"]+)"/g))e[id]=new E();e['sb-k'].value='598';e['sb-m'].value='1216';vm.runInNewContext(js,{window:{SBFD:C,addEventListener:(t,f)=>events[t]=f},document:{getElementById:id=>{a.ok(e[id],id);return e[id];},createElement:()=>new E(),createElementNS:()=>new E()}});return {e,events};}
const rows=e=>e.children.map(r=>r.children.map(c=>c.textContent)),paths=e=>e.children.filter(n=>n.attrs.d).map(n=>n.attrs.d);
test('SBFD DOM default counters, exact source indices and numeric alternatives',()=>{const {e}=setup();a.match(e['sb-result'].textContent,/598\+598\+598\+254=2048/);a.match(e['sb-result'].textContent,/25.66784925 m.*0.155648 s.*0.141624454 m\/s/);a.deepEqual(rows(e['sb-blocks']).filter(r=>r[0]!=='全局空格'),[['感知节点1','65','662','598'],['感知节点2','726','1323','598'],['通信节点3','1387','1984','598']]);a.equal(e['sb-samples'].children.length,10);a.match(e['sb-range-caption'].textContent,/假想全格参考.*7.49481145/);});
test('K changes range/resources but leaves velocity curve fixed; captions and outputs update',()=>{const {e}=setup(),range=paths(e['sb-range']),velocity=paths(e['sb-velocity']);for(const K of [128,880]){e['sb-k'].value=String(K);e['sb-k'].fire('input');a.equal(e['sb-k-out'].textContent,String(K));a.match(e['sb-allocation-caption'].textContent,new RegExp('通信 '+(1794-2*K)+' 格'));a.notDeepEqual(paths(e['sb-range']),range);a.deepEqual(paths(e['sb-velocity']),velocity);for(const id of ['sb-range-caption','sb-velocity-caption','sb-metrics'])a.ok(e[id].textContent.includes('K='+K));a.match(e['sb-k'].attrs['aria-valuetext'],new RegExp(String(K)));}});
test('M changes velocity, not resource/range; out-of-domain null described; repeated reset works',()=>{const {e}=setup(),initial=e['sb-result'].textContent,range=paths(e['sb-range']),velocity=paths(e['sb-velocity']),blocks=rows(e['sb-blocks']);for(const M of [128,2432]){e['sb-m'].value=String(M);e['sb-m'].fire('input');a.deepEqual(paths(e['sb-range']),range);a.deepEqual(rows(e['sb-blocks']),blocks);a.notDeepEqual(paths(e['sb-velocity']),velocity);a.equal(e['sb-m-out'].textContent,String(M));a.match(e['sb-velocity-caption'].textContent,new RegExp('M='+M));if(M===128)a.match(e['sb-velocity-caption'].textContent,/超出/);}for(let i=0;i<2;i++){e['sb-reset'].fire('click');a.equal(e['sb-result'].textContent,initial);a.equal(e['sb-k'].value,'598');a.equal(e['sb-m'].value,'1216');}});
test('all SVG states finite at actual narrow/wide widths; redraw preserves state and accessible names',()=>{for(const width of [240,270,323,388,720,950]){const {e,events}=setup(width);for(const K of [128,598,880])for(const M of [128,1216,2432]){e['sb-k'].value=String(K);e['sb-m'].value=String(M);e['sb-k'].fire('input');for(const id of ['sb-allocation','sb-range','sb-velocity']){a.ok(e[id].attrs.viewBox.startsWith('0 0 '+width+' '));a.ok(e[id].children.every(n=>!(/NaN|Infinity|undefined/.test(JSON.stringify(n.attrs)))));a.ok(e[id].children.some(n=>n.attrs.id===id+'-title'));a.ok(e[id].children.some(n=>n.attrs.id===id+'-desc'));}const before=e['sb-result'].textContent;events.resize();a.equal(e['sb-result'].textContent,before);}}});
test('static semantics, source/model separation and no network/animation code',()=>{for(const id of ['k','m'])a.match(html,new RegExp('for="sb-'+id+'"'));for(const phrase of ['0.145 m/s','0.1416244545 m/s','每种模式分别有几次不明确','多基地感知仍是未来工作','不是论文实测数据','不是论文的多频带波形','接收机饱和']){a.ok(html.includes(phrase),phrase);}a.match(html,/<noscript>/);a.match(html,/aria-live="polite"/);a.match(html,/type="range"/);a.ok(!/setInterval|requestAnimationFrame|fetch\(|XMLHttpRequest/.test(js));});
test('local entry links, prerequisite anchors and resources resolve',()=>{for(const file of ['sbfd-resource.html','foundations.html','theory.html']){const h=fs.readFileSync(require.resolve('../'+file),'utf8');for(const [,url]of h.matchAll(/(?:href|src)="([^"]+)"/g)){if(/^https?:/.test(url))continue;const [target,hash]=url.split('#'),name=(target||file).split('?')[0];const content=fs.readFileSync(require.resolve('../'+name),'utf8');if(hash)a.ok(content.includes(`id="${hash}"`),`${file}: ${url}`);}}});
