const {test}=require('node:test');
const a=require('node:assert/strict');
const C=require('../course-core.js'),V=require('../velocity-core.js');
const {Tr}=C.cfg,lambda=C.C/C.cfg.fc;
const near=(x,y,t=1e-9)=>a.ok(Math.abs(x-y)<t,`${x} != ${y}`);
const col=(s,r=4)=>s.A.map(row=>row[r]);
test('two-snapshot inverse yields observed 45deg, 250Hz, 7.5m/s',()=>{const p=V.adjacent(col(C.ofdm()),Tr,lambda);near(p.phase,Math.PI/4);near(p.fd,250);near(p.v,7.5);});
test('candidate 7.5 cancels each actual complex sample, not just one angle',()=>{const s=V.match(col(C.ofdm()),7.5,Tr,lambda);near(s.step,Math.PI/4);s.rotated.forEach(z=>{near(z.re,1);near(z.im,0);});near(s.power,1);near(s.coherence,1);});
test('wrong candidates 0 and 3.75 cancel over all 16 snapshots',()=>{for(const v of [0,3.75])near(V.match(col(C.ofdm()),v,Tr,lambda).power,0);});
test('partial sum of a matched column grows by exactly 1/M per sample',()=>{const s=V.match(col(C.ofdm()),7.5,Tr,lambda);s.partial.forEach((z,i)=>{near(z.re,(i+1)/16);near(z.im,0);});});
test('all 16 candidate sums equal the real DFT complex output in all range columns',()=>{for(const [R,v,remove] of [[37.5,7.5,true],[43.2,-6.3,true],[37.5,7.5,false],[0,0,true]]){const s=C.ofdm(R,v,remove);for(let r=0;r<16;r++)V.grid(col(s,r),Tr,lambda).forEach(q=>{near(q.sum.re,s.D[q.q][r].re);near(q.sum.im,s.D[q.q][r].im);});}});
test('signed d=-2 maps to q=14, -250Hz, -7.5m/s',()=>{const s=C.ofdm(37.5,-7.5),best=V.grid(col(s),Tr,lambda).sort((a,b)=>b.power-a.power)[0];a.equal(best.d,-2);a.equal(best.q,14);near(best.fd,-250);near(best.v,-7.5);});
test('unknown common initial phase is preserved, not forced to zero',()=>{const rotate={re:.7*Math.cos(.83),im:.7*Math.sin(.83)},z=col(C.ofdm()).map(x=>C.mul(x,rotate)),s=V.match(z,7.5,Tr,lambda);near(s.sum.re,rotate.re);near(s.sum.im,rotate.im);near(s.power,.49);near(V.adjacent(z,Tr,lambda).v,7.5);});
test('power-only data produces zero-Doppler peak, losing true speed',()=>{const z=col(C.ofdm()).map(q=>({re:C.power(q),im:0}));const best=V.grid(z,Tr,lambda).sort((a,b)=>b.power-a.power)[0];near(best.v,0);near(V.match(z,7.5,Tr,lambda).power,0);});
test('empty range bin does not report a meaningless phase speed',()=>{const z=col(C.ofdm(),1);a.equal(V.adjacent(z,Tr,lambda),null);a.equal(V.match(z,7.5,Tr,lambda).coherence,null);});
test('off-grid peak leaks while continuous matching recovers coherent maximum',()=>{const z=col(C.ofdm(37.5,8.1));near(V.match(z,8.1,Tr,lambda).power,1);a.ok(Math.max(...V.grid(z,Tr,lambda).map(a=>a.power))<.99);});
test('candidate speeds separated by lambda/(2Tr) are aliased',()=>{const z=col(C.ofdm());near(V.match(z,7.5,Tr,lambda).power,V.match(z,67.5,Tr,lambda).power);near(V.match(z,30,Tr,lambda).power,V.match(z,-30,Tr,lambda).power);});
test('two resolvable same-range targets yield two velocity components',()=>{const p=col(C.ofdm(37.5,7.5)),q=col(C.ofdm(37.5,-7.5)),z=p.map((x,i)=>({re:x.re+.65*q[i].re,im:x.im+.65*q[i].im}));const bins=V.grid(z,Tr,lambda).sort((a,b)=>b.power-a.power);near(bins[0].v,7.5);near(bins[0].power,1);near(bins[1].v,-7.5);near(bins[1].power,.65**2);});
test('invalid sample, speed and sampling parameters fail explicitly',()=>{a.throws(()=>V.match([],0,Tr,lambda));a.throws(()=>V.match([{re:0,im:0},{re:NaN,im:0}],0,Tr,lambda));a.throws(()=>V.match(col(C.ofdm()),Infinity,Tr,lambda));a.throws(()=>V.grid(col(C.ofdm()),0,lambda));a.throws(()=>V.adjacent(col(C.ofdm()),Tr,-1));});
