// Dependency-free DOM execution; does not certify a real browser or keyboard.
const {test}=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),C=require('../waveform-core.js'),D=require('../data/waveform-states.json');
const html=fs.readFileSync(require.resolve('../waveform-design.html'),'utf8'),script=fs.readFileSync(require.resolve('../waveform.js'),'utf8');
async function setup(width=600,badFetch=false){class E{constructor(){this.children=[];this.attrs={};this.events={};this.clientWidth=width;this.value='';this.textContent='';}setAttribute(k,v){this.attrs[k]=String(v);}append(...n){this.children.push(...n);}replaceChildren(...n){this.children=n;}addEventListener(t,f){this.events[t]=f;}fire(t){a.ok(this.events[t]);this.events[t]({target:this});}}
const els={},events={};for(const [,id]of html.matchAll(/\bid="([^"]+)"/g))els[id]=new E();for(const [id,value]of [['wf-channel','complex'],['wf-beta','0.8'],['wf-angle','0'],['wf-user','0']])els[id].value=value;
vm.runInNewContext(script,{window:{WaveformCore:C,addEventListener:(t,f)=>events[t]=f},fetch:()=>badFetch?Promise.reject(Error('offline')):Promise.resolve({ok:true,json:()=>Promise.resolve(D)}),document:{getElementById:id=>{a.ok(els[id],id);return els[id];},createElement:()=>new E(),createElementNS:()=>new E()}});await new Promise(r=>setImmediate(r));return {els,events};}
const rows=e=>e['wf-metrics'].children.map(n=>n.children.map(n=>n.textContent));
test('all 27 selector states and both users produce matching DOM values; reset is repeatable',async()=>{const {els:e,events}=await setup(),initial=e['wf-status'].textContent,initialRows=rows(e);a.equal(initialRows.length,4);
for(const s of D.states){e['wf-channel'].value=s.channel;e['wf-beta'].value=String(s.beta);e['wf-angle'].value=String(s.angle);for(const user of ['0','1']){e['wf-user'].value=user;e['wf-user'].fire('change');a.ok(e['wf-status'].textContent.includes(s.id));const v=C.evaluate(D.channels[s.channel],D.symbols,s.R,s.optimal,s.lowerBound);a.equal(rows(e)[0][2],v.mse.toFixed(5));a.equal(e['wf-symbols'].children.filter(n=>n.attrs.r===String(4)).length,8);}}
for(let i=0;i<3;i++){e['wf-reset'].fire('click');a.equal(e['wf-status'].textContent,initial);a.deepEqual(rows(e),initialRows);a.equal(e['wf-user'].value,'0');a.equal(e['wf-channel'].value,'complex');a.equal(e['wf-beta'].value,'0.8');a.equal(e['wf-angle'].value,'0');events.resize();a.deepEqual(rows(e),initialRows);}});
test('responsive SVG uses CSS-pixel viewBox and bounded finite plot points',async()=>{for(const width of [240,270,293,323,358,388,600,950]){const {els:e}=await setup(width);for(const id of ['wf-pattern','wf-symbols','wf-time']){const svg=e[id];a.equal(svg.attrs.viewBox,`0 0 ${width} 300`);for(const n of svg.children){a.ok(!/NaN|Infinity/.test(JSON.stringify(n.attrs)));if(n.attrs.points)for(const pair of n.attrs.points.split(' ')){const [x,y]=pair.split(',').map(Number);a.ok(x>=0&&x<=width&&y>=0&&y<=300);}}}}a.match(fs.readFileSync(require.resolve('../waveform.css'),'utf8'),/font-size:14px/);});
test('network and invalid-state failures are visible and clear old charts and metrics',async()=>{const {els:offline}=await setup(323,true);a.match(offline['wf-status'].textContent,/失败/);for(const id of ['wf-pattern','wf-symbols','wf-time','wf-metrics'])a.equal(offline[id].children.length,0);const {els:e}=await setup();a.ok(e['wf-pattern'].children.length);e['wf-channel'].value='bad';e['wf-channel'].fire('change');a.match(e['wf-status'].textContent,/图表已清空/);for(const id of ['wf-pattern','wf-symbols','wf-time','wf-metrics'])a.equal(e[id].children.length,0);e['wf-reset'].fire('click');a.match(e['wf-status'].textContent,/已载入 complex:0.8:0/);});
test('all controls are labelled and there is no autoplay',()=>{for(const id of ['wf-channel','wf-beta','wf-angle','wf-user'])a.match(html,new RegExp(`for="${id}"`));a.match(html,/type="button" id="wf-reset"/);a.match(html,/<noscript>/);a.ok(!/setInterval|requestAnimationFrame|Math.random/.test(script));});
