'use strict';
// The map is an editorial overlay. All existing science/evidence resolves from the registry.
module.exports=function renderMap(r){
 const k=r.knowledgeMap, esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;');
 const link=(h,t)=>`<a href="${esc(h)}">${esc(t)}</a>`, unit=id=>r.units.find(u=>u.id===id), direction=id=>r.directions.find(d=>d.id===id), caseFor=id=>r.cases.find(c=>c.id===id);
 const ids=new Set([...k.nodes,...k.directionNodes].map(n=>n.id)),groups=new Set(k.groups.map(g=>g.id));
 if(ids.size!==k.nodes.length+k.directionNodes.length)throw new Error('Duplicate knowledge-map node ID');
 for(const n of k.nodes){if(!groups.has(n.groupId)||n.unitRefs.some(id=>!unit(id))||n.entryUnitRef&&!unit(n.entryUnitRef)||!n.entryUnitRef&&!n.href)throw new Error('Invalid knowledge-map concept reference: '+n.id);}
 for(const n of k.directionNodes){if(n.registryRef.collection!=='directions'||!direction(n.registryRef.id)||!groups.has(n.groupId))throw new Error('Invalid knowledge-map direction reference: '+n.id);}
 for(const e of k.edges){if(!ids.has(e.source)||!ids.has(e.target)||!k.edgeTypes.some(t=>t.id===e.type)||e.provenance!=='editorial-pedagogic'||e.scientificClaim!==false)throw new Error('Invalid knowledge-map editorial relation');}
 for(const b of k.bands)if(b.groupIds.some(id=>!groups.has(id)))throw new Error('Invalid knowledge-map band reference');
 const nodes=k.nodes.map(n=>({...n,href:n.entryUnitRef?unit(n.entryUnitRef).href:n.href})).concat(k.directionNodes.map(n=>{const d=direction(n.registryRef.id);return {...n,label:d.title,question:d.question,href:'reading.html#direction-'+d.id,direction:d};}));
 const node=id=>nodes.find(n=>n.id===id), anchor=id=>'map-node-'+id.replace(':','-'), button=(id,label)=>`<button type="button" data-map-node="${esc(id)}" aria-controls="map-detail" hidden>${esc(label)}</button>`;
 const list=items=>'<ul>'+items.map(s=>'<li>'+esc(s)+'</li>').join('')+'</ul>';
 function evidence(c){const p=c.paperComparison;if(!p)return `<p>${link('reading.html#'+c.id,c.title)}：逐项对照待整理</p>`;
 return `<details class="map-deep"><summary>${esc(c.title)} · 部分核对</summary><p>${esc(p.verificationNote)}</p><dl class="map-facts"><dt>固定原文与版本</dt><dd>${link(p.sourceUrl,p.sourceTitle)} · ${esc(p.version)}</dd><dt>章节 / 图 / 公式</dt><dd>${esc(p.locator.summary)}</dd><dt>论文证据</dt><dd>${esc(p.paperEvidenceType)}</dd><dt>本站证据</dt><dd>${esc(p.siteArtifactType)}</dd><dt>保留条件</dt><dd>${list(p.retainedAssumptions)}</dd><dt>省略机制</dt><dd>${list(p.omittedMechanisms)}</dd><dt>指标与预算</dt><dd>${list(p.metrics)}${esc(p.resourceBudget.summary)}</dd><dt>待核对 / 未复现</dt><dd>${list(p.unknowns)}</dd></dl>${link('reading.html#'+c.id,'进入原文对照 →')}</details>`;}
 function relations(n){const edges=k.edges.filter(e=>e.source===n.id||e.target===n.id);const units=(n.unitRefs||[]).map(unit);const types=k.edgeTypes.filter(t=>edges.some(e=>e.type===t.id)||t.id==='evidence'&&units.length);
 const rows=edges.map(e=>{const t=k.edgeTypes.find(t=>t.id===e.type),other=node(e.source===n.id?e.target:e.source);return `<li data-map-relation="${e.type}"><span class="map-relation-type">${esc(t.label)}</span><p>${t.directed?esc(node(e.source).label)+' → '+esc(node(e.target).label):esc(other.label)}</p><p>${esc(e.label)}<small>${esc(t.meaning)}</small></p>${button(other.id,'探索 '+other.label)}</li>`;}).concat(units.map(u=>`<li data-map-relation="evidence"><span class="map-relation-type">证据 / 机制</span><p>${link(u.href,u.title)}</p><p>${esc(u.action)}<small>本站机制演示，不等于整篇论文复现</small></p></li>`));
 return `<div class="map-local-map"><h4>局部关系 · ${rows.length} 条</h4><p class="map-center-node">${esc(n.label)}</p><p class="small">箭头只表示建议先修或研究入口；其余关系不设方向。所有关系均为教学导航。</p><div class="map-filters" aria-label="筛选局部关系"><button type="button" data-map-filter="all" aria-pressed="true" hidden>全部关系</button>${types.map(t=>`<button type="button" data-map-filter="${t.id}" aria-pressed="false" hidden>${esc(t.label)}</button>`).join('')}</div><p data-map-relation-status role="status" aria-live="polite"></p><ul class="map-relations">${rows.join('')}</ul></div>`;}
 function content(n){if(n.direction){const d=n.direction;return `<p>${esc(d.question)}</p><p class="map-boundary">${esc(d.scope)}</p><p>当前覆盖：${esc(d.coverage)}</p><ol class="map-direction-list">${d.levels.map(l=>`<li><strong>${esc(l.label)}</strong>${l.note?'<p>'+esc(l.note)+'</p>':''}${l.notice?'<p>'+esc(l.notice)+'</p>':''}<ul>${l.items.map(i=>`<li>${i.status==='available'?link(i.href,i.label):esc(i.label)+'（尚未实现）'}${i.scope==='foundation-only'?' · 仅前置实验':''}${i.scope==='shared-template'?' · 通用计划':''}${i.note?'<p>'+esc(i.note)+'</p>':''}</li>`).join('')}</ul></li>`).join('')}</ol><p class="map-boundary">后续可扩展（未实现）：${esc(d.nextExtension)}</p>${d.primaryCaseIds.map(id=>evidence(caseFor(id))).join('')}${relations(n)}`;}
 const units=n.unitRefs.map(unit),cases=r.cases.filter(c=>n.unitRefs.includes(c.unit));return `<p>${esc(n.question)}</p><dl class="map-facts"><dt>已知、观测与未知</dt><dd>${esc(n.knownUnknown)}</dd></dl><p class="map-boundary"><strong>适用边界</strong> ${esc(n.boundary)}</p><div class="map-actions">${link(n.href,'读这一节 →')}${units[0]?'<p><strong>下一步动手：</strong>'+esc(units[0].action)+'</p>'+link(units[0].href,'进入机制实验 →'):'<p>此概念尚无独立专项实验；先沿已有讲解核对观测与假设。</p>'}</div>${relations(n)}${cases.length?'<h4>原文与本站证据</h4>'+cases.map(evidence).join(''):''}<p>${link('practice.html#notebook','把假设与观察记入研究记录 →')}</p>`;}
 function entry(n){return `<li id="${anchor(n.id)}" data-map-entry="${esc(n.id)}" data-map-group="${n.groupId}" data-map-search="${esc([n.label,n.question,...(n.unitRefs||[]).map(id=>unit(id).title)].join(' '))}">${link(n.href,n.label)}${button(n.id,'查看关系')}</li>`;}
 function group(g){const ns=nodes.filter(n=>n.groupId===g.id),index=k.groups.indexOf(g)+1;return `<details id="map-group-${g.id}" class="map-group" data-map-group="${g.id}"><summary><span class="map-number">${String(index).padStart(2,'0')}</span><span class="map-group-name">${esc(g.label)}</span><span class="map-group-question">${esc(g.question)}</span><span class="map-count">${ns.length?ns.length+' 个'+(g.kind==='concepts'?'概念':'方向'):r.units.length+' 个实验 · '+r.cases.length+' 个专题'}<span class="map-disclosure-closed"> · 展开</span><span class="map-disclosure-open"> · 已展开</span></span></summary>${ns.length?'<ul class="map-node-list">'+ns.map(entry).join('')+'</ul>':`<ul class="map-node-list"><li>${link('experiments.html','机制实验目录')}</li><li>${link('reading.html#cases','专题原文对照')}</li><li>${link('reading.html#reading','原文与证据目录')}</li><li>${link('practice.html#notebook','研究记录与复核')}</li></ul>`}</details>`;}
 const overview=`<p class="map-kicker">从一个问题开始</p><h3 id="map-detail-title">先看关系，再选路径</h3><p>展开地图主题，选择“查看关系”，理解概念的先修、边界与下一步。直接点概念名称，进入讲解。</p><div class="map-actions">${link('foundations.html#echo','我想理解回波 →')}${link('reading.html#directions','我想找一个研究问题 →')}</div><p class="map-boundary">机制演示、理论界、论文证据各有适用范围。这里的连接帮助阅读，不替代证明。</p>`;
 return `<section id="knowledge-map" class="knowledge-map" aria-labelledby="map-title"><header class="map-heading"><p class="eyebrow">FIELD NOTES / 从基础到研究</p><h2 id="map-title">${esc(k.title)}</h2><p>电波怎样成为观测，观测怎样支持判断，设计又怎样受到现实约束？</p><p class="map-disclaimer">${esc(k.disclaimer)}</p></header><form class="map-tools" role="search" hidden><label for="map-search">找概念、实验或研究方向</label><input id="map-search" type="search" autocomplete="off" placeholder="试试：相位、CRB、导频"><button type="reset">清除搜索</button><button type="button" class="map-overview-button" data-map-reset>返回全景</button><p id="map-status" role="status" aria-live="polite"></p><ul class="map-search-results" id="map-search-results" hidden></ul></form><div class="map-workspace"><div class="map-atlas">${k.bands.map(b=>`<div class="map-band" data-tone="${b.tone}"><p class="map-band-label">${esc(b.label)}</p><div class="map-band-groups">${b.groupIds.map(id=>group(k.groups.find(g=>g.id===id))).join('')}</div></div>`).join('')}</div><section class="map-detail" id="map-detail" tabindex="-1" aria-labelledby="map-detail-title">${overview}</section></div><template id="map-overview">${overview.replace(' id="map-detail-title"','')}</template>${nodes.map(n=>`<template id="map-template-${esc(n.id)}"><p class="map-breadcrumb">全景 / ${esc(k.groups.find(g=>g.id===n.groupId).label)}</p><p class="map-kicker">已选择 · ${n.direction?'研究方向':'核心概念'}</p><h3>${esc(n.label)}</h3>${content(n)}</template>`).join('')}<p class="map-curriculum-link">${link('#curriculum','需要一条顺序路线？沿四个阶段安排学习 ↓')}</p></section>`;
};
